spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaozefeng/spring-cloud-config
          username: qq523107430@gmail.com
          password: 857269425xx
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
management:
  endpoint:
    bus-refresh:
      enabled: true
  # 相对之前的版本，这里要暴露所有的断点
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoints:
#    web:
#      expose: "*"