spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081


